### ISSUE TITLE
Database upgrade problem from 8.1 to 10

### ISSUE THREAD

**Issue by help-14** [demigor/lex.db#41]
Hi, when testing upgrade compatible from Windows 8.1 app to Windows 10 by coping the db folder, I got this error (items class are the same)

Unknown type code 101
   at Lex.Db.Serialization.DbTypes.GetType(Int16 type)
   at Lex.Db.Serialization.DbType..ctor(SByte id)
   at Lex.Db.Serialization.DbType.Read(DataReader reader)
   at Lex.Db.MemberMap..ctor(DataReader reader)
   at Lex.Db.MemberMap`1..ctor(DataReader reader)
   at Lex.Db.Mapping.Metadata`1..ctor(DataReader reader, UInt32 hash)
   at Lex.Db.Mapping.Metadata`1.Read(DataReader reader)
   at Lex.Db.DbTable`1.ReadIndexes(Stream stream)
   at Lex.Db.DbTable`1.Read(IDbTableReader reader)
   at Lex.Db.DbInstance.BulkReadScope.GetReader(DbTable table)
   at Lex.Db.DbTable`1.ReadScope()
   at Lex.Db.DbTable`1.<GetEnumerator>d__88.MoveNext()
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
   at MoneyLover.Db.Task.GetUserTask.<DoQuery>d__0.MoveNext()

This is the class:

public class users
    {
        public int id { get; set; }
        public string user_sync_id { get; set; }
        public string access_token { get; set; }
        public string email { get; set; }
        public int gold { get; set; }
        public long last_sync { get; set; }
        public int lock_type { get; set; }
        public string hash_pass { get; set; }
        public int account_default { get; set; }
        public long last_sync_campaign { get; set; }
        public long last_sync_budget { get; set; }
    }

**Comment by help-14** [comment]
Oops never mind I figure it out, my lexdb code is not updated.
